//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anko.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anko.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {agent},
        ///
        ///We have new booking:
        ///
        ///{table}
        ///
        ///Please confirm that it will be loaded on the scheduled vessel without delay.
        ///
        ///Thanks
        ///.
        /// </summary>
        internal static string BookingConfirmationMail {
            get {
                return ResourceManager.GetString("BookingConfirmationMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {agent},
        ///
        ///Please send me the relevant documents for the following orders:
        ///
        ///{table}
        ///
        ///Thanks
        ///.
        /// </summary>
        internal static string DocumentsReceipts {
            get {
                return ResourceManager.GetString("DocumentsReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {agent},
        ///
        ///Tommorow ({date}, {day}) we have loading for:
        ///
        ///{table}
        ///
        ///Please confirm that everything is on order.
        ///
        ///Thanks
        ///.
        /// </summary>
        internal static string LoadingConfirmationMail {
            get {
                return ResourceManager.GetString("LoadingConfirmationMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שלום לכולם,
        ///מצ&apos;ב דו&apos;ח סטטוס הזמנות הפתוחות אצלנו במערכת.
        ///ההגעה הקרובה היא בתאריך: {arrivalDate}
        ///סה&apos;כ הזמנות: {totalNumOfOrders}
        ///תודה ויום טוב..
        /// </summary>
        internal static string OrdersMail {
            get {
                return ResourceManager.GetString("OrdersMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Regards,
        ///Anna Raitin
        ///Tel: 972.4.8108818 Ext.852
        ///Fax: 972.4.8524645
        ///e-mail: anna@tanko.global
        ///Web site: www.tanko.global.
        /// </summary>
        internal static string SignatureText {
            get {
                return ResourceManager.GetString("SignatureText", resourceCulture);
            }
        }
    }
}
